### PR TITLE
Save files graciously with respecting their modification time

### PR DESCRIPTION
**Pull request by svgol**
>    where is the "fixed a memleakin the -[openFileAtPath:editorManager:editable:] ":

`NSMutableDictionary *attributes = [NSMutableDictionary new];`
`....`
`attributedString = [attributedString initWithString:text attributes:attributes];`

the local var '**attributes**' is not released at the end, only '**attributedString**'

Added
 
`RELEASE(attributes)`

### CODE REVIEW

**Comment by rmottola** [comment]
I like this suggestion and concept. I don't like too much the "backup" option... shouldn't it perhaps be more standard to either "force" overwrite or cancel? That is a typical behaviour from other editors. Being inside a project would maybe even imply a rename, too much hassle.
Also I need to check that autosave doesn't interfere, maybe it should be skipped? 

I will start by working in your modification time tracking, which is the base and see.

**Comment by svgol** [comment]
>  I don't like too much the "backup" option... shouldn't it perhaps be more standard to either "force" overwrite or cancel? 

fixed

>  to check that autosave doesn't interfere

it seems the autosave feature doesn't touch source files

**Comment by rmottola** [comment]
I worked on your concept: would you mind checking the new branch on ProjectCenter? It only spits out a warning, but I tried refining your modification date logic. Tell me what you think, completing with your work will be easy

**Comment by svgol** [comment]
I don't understand the new chunk in the -[saveFileTo:]. You store at **path** and save the modification time of **_path**. It looks for me unreasonable.

**Comment by rmottola** [comment]
> I don't understand the new chunk in the -[saveFileTo:]. You store at **path** and save the modification time of **_path**. It looks for me unreasonable.

You are right, it is a copy&paste error.. the path can be different (actually, most probably will). Fix!
However, thinking more, I think it is not correct to keep track of the date in saveFileTo, excess of zeal on my side. "Save To" makes a copy of a file, further saves will be on the original path, so checking the date is not needed. At most a simple warning about "overwrite" of the externa lfile is needed, which is already implemented.

**Comment by rmottola** [comment]
I completed implementation, also allow the option to reload the external data.
Thanks for the suggestions. Give it a spin!

**Pull request closed without merging**
