### PR TITLE
Centered information panel.

### PR DESCRIPTION
**Pull request by armm77**

### CODE REVIEW

**Comment by rmottola** [comment]
I don't think the panel should be forcibly centered everytime, it is annoying. It is best left were it previously was, as usual for panels.

**Comment by gcasa** [comment]
Every info panel about every app is centered EVERY time, @rmottola

**Comment by gcasa** [comment]
Yes, I know I did this without your approval @rmottola, but it looks really stupid off center.

**Comment by rmottola** [comment]
> Yes, I know I did this without your approval @rmottola, but it looks really stupid off center.

Will be reverted as explained above.

**Comment by rmottola** [comment]
> Yes, I know I did this without your approval @rmottola, but it looks really stupid off center.



> _facepalm_ Every info panel about every app is centered EVERY time, @rmottola 

_facepalm_ yourself, @gcasa try your own application, Gorm! try GWorkspace, try EasyDiff! It is centered *the first time* but not subsequent invocations inside an application session! And that it should be and not what this patch does. PC indeed is broken in this regard, but this PR is wrong.

**Pull request merged**
